### ISSUE TITLE
Needs bump to 1.18.1

### ISSUE THREAD

**Issue by 5cript** [Favouriteless/SoulTrap-Fabric#2]
The mods doesnt load in 1.18.1, but is probably going to be fine (?).
Needs a new release with the bump because new mods (and newly updated mods) start to refuse 1.18 compatibility due to the log4j debacle.

**Comment by Favouriteless** [comment]
Ah thanks for letting me know, I'll get this working asap

**Comment by Favouriteless** [comment]
Now fixed in the latest version.
